### ISSUE TITLE
rat?

### ISSUE THREAD

**Issue by randomthingy9803** [AstrqlDev/Pizza-Client#1]
rat or no

**Comment by Vaporsdeath** [comment]
no

**Comment by Polarr21** [comment]
Yes its obviously a rat. use your brain. Join the pizza discord for the real one.

**Comment by Vaporsdeath** [comment]
it is

**Comment by randomthingy9803** [comment]
well shit

**Comment by Mspy1** [comment]
it's rat.

**Comment by Mspy1** [comment]
someone's got ratted on pizza discord from this jar ahahahaha session id stealer.
